# Arthachitra Tick Engine Configuration

app:
  name: "arthachitra-tick-engine"
  version: "1.0.0"
  log_level: "INFO"

redis:
  host: "localhost"
  port: 6379
  password: ""
  database: 0
  connection_timeout: 5
  command_timeout: 1

market_data:
  symbols:
    - "NIFTY"
    - "BANKNIFTY"
    - "RELIANCE"
    - "TCS"
    - "HDFCBANK"
    - "INFY"
    - "ICICIBANK"
  
  processing:
    batch_size: 1000
    max_queue_size: 100000
    tick_buffer_size: 10000
    
  publication:
    order_book_depth: 10
    publish_interval_ms: 10
    compression: true

performance:
  worker_threads: 4
  memory_pool_size: "100MB"
  cpu_affinity: true
  
logging:
  level: "INFO"
  file: "/var/log/arthachitra/tick-engine.log"
  max_size: "50MB"
  max_files: 5

monitoring:
  metrics_port: 9091
  health_check_port: 8080
