apiVersion: apps/v1
kind: Deployment
metadata:
  name: arthachitra-frontend
  namespace: arthachitra-prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: arthachitra-frontend
  template:
    metadata:
      labels:
        app: arthachitra-frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/yourusername/arthachitra-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "https://api.arthachitra.com"
        - name: NEXT_PUBLIC_WS_URL
          value: "wss://api.arthachitra.com"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arthachitra-backend
  namespace: arthachitra-prod
spec:
  replicas: 5
  selector:
    matchLabels:
      app: arthachitra-backend
  template:
    metadata:
      labels:
        app: arthachitra-backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/yourusername/arthachitra-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: arthachitra-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: arthachitra-secrets
              key: redis-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: arthachitra-secrets
              key: jwt-secret
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arthachitra-ml
  namespace: arthachitra-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: arthachitra-ml
  template:
    metadata:
      labels:
        app: arthachitra-ml
    spec:
      containers:
      - name: ml-service
        image: ghcr.io/yourusername/arthachitra-ml-service:latest
        ports:
        - containerPort: 8001
        env:
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: arthachitra-secrets
              key: redis-url
        resources:
          requests:
            memory: "1Gi"
            cpu: "1000m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        volumeMounts:
        - name: model-storage
          mountPath: /app/models
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: ml-models-pvc
