apiVersion: v1
kind: Secret
metadata:
  name: arthachitra-secrets
  namespace: arthachitra-prod
type: Opaque
stringData:
  database-url: "postgresql://username:password@postgres:5432/arthachitra"
  redis-url: "redis://redis:6379"
  jwt-secret: "your-super-secret-jwt-key-change-in-production"
  zerodha-api-key: "your-zerodha-api-key"
  zerodha-api-secret: "your-zerodha-api-secret"
  binance-api-key: "your-binance-api-key"
  binance-api-secret: "your-binance-api-secret"
  smtp-username: "your-smtp-username"
  smtp-password: "your-smtp-password"
  sentry-dsn: "your-sentry-dsn"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: arthachitra-config
  namespace: arthachitra-prod
data:
  APP_ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  API_V1_STR: "/api/v1"
  CORS_ORIGINS: '["https://arthachitra.com"]'
  RATE_LIMIT_DEFAULT: "1000/minute"
  RATE_LIMIT_AUTHENTICATED: "5000/minute"
